from __future__ import annotations

import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from bug_triage.models import BugRecord, TestCandidate, TriageRecommendation
from bug_triage.services.testgen import TestGenerationService


class FakeLLMClient:
    enabled = True
    mode_label = "openai (fake)"

    def generate_test_candidate(
        self,
        *,
        bug: BugRecord,
        triage: TriageRecommendation,
        generated_tests_dir: Path,
    ) -> TestCandidate:
        file_path = generated_tests_dir / "bug_18_llm.cs"
        file_path.write_text("// llm-generated", encoding="utf-8")
        return TestCandidate(
            id=None,
            bug_id=bug.id or 0,
            test_type="platform-regression",
            file_path=str(file_path),
            framework="Unity Test Framework",
            generated_code="// llm-generated",
            status="generated",
            execution_summary="Generated by fake llm",
        )


class TestGenerationServiceTests(unittest.TestCase):
    def test_generate_unity_regression_writes_file(self) -> None:
        bug = BugRecord(
            id=18,
            source="jira",
            external_id="GAME-18",
            game_title="Starfall Arena",
            platform="mobile",
            engine="Unity",
            build_number="Android-2.7.4",
            title="Android matchmaking fails after party leader changes region",
            description="Queueing after region swap disconnects the party leader.",
        )
        triage = TriageRecommendation(
            id=None,
            bug_id=18,
            summary="Matchmaking flow failure",
            severity="high",
            priority="P1",
            component="networking",
            owner_team="Online Services",
            confidence=0.84,
            duplicate_of_id=None,
            probable_root_cause="Likely lobby session-state bug.",
            next_action="Add regression coverage.",
            evidence=[],
        )

        output_dir = Path(__file__).resolve().parents[1] / "generated_tests"
        output_dir.mkdir(exist_ok=True)

        service = TestGenerationService(output_dir)
        candidate = service.generate(bug, triage)

        self.assertEqual(candidate.test_type, "network-regression")
        self.assertEqual(candidate.framework, "Unity Test Framework")
        self.assertTrue(candidate.file_path.endswith(".cs"))
        self.assertTrue(Path(candidate.file_path).exists())
        self.assertIn("[UnityTest]", candidate.generated_code)

    def test_uses_llm_client_when_available(self) -> None:
        bug = BugRecord(
            id=18,
            source="jira",
            external_id="GAME-18",
            game_title="Starfall Arena",
            platform="console",
            engine="Unity",
            build_number="PS5-1.3.18",
            title="Resume flow lockup",
            description="Inventory resume flow lockup on PS5.",
        )
        triage = TriageRecommendation(
            id=None,
            bug_id=18,
            summary="Resume flow failure",
            severity="high",
            priority="P1",
            component="platform_compliance",
            owner_team="Platform",
            confidence=0.84,
            duplicate_of_id=None,
            probable_root_cause="Resume handling issue.",
            next_action="Add regression coverage.",
            evidence=[],
        )

        output_dir = Path(__file__).resolve().parents[1] / "generated_tests"
        output_dir.mkdir(exist_ok=True)

        service = TestGenerationService(output_dir, llm_client=FakeLLMClient())
        candidate = service.generate(bug, triage)

        self.assertEqual(candidate.framework, "Unity Test Framework")
        self.assertIn("llm-generated", candidate.generated_code)
        self.assertEqual(service.mode_label, "openai (fake)")


if __name__ == "__main__":
    unittest.main()
